"""Per-country cultural observance data.

Separated from the observance engine (observances.py)
so the engine stays pure logic and this stays a data table. The GB/US/CA sets
are hand-curated; the remaining countries were compiled and date-verified by a
multi-agent research pass and every entry is validated against the engine.
"""

from __future__ import annotations

from datetime import date

from calendar_app.core.observances import (
    Observance,
    MONDAY,
    THURSDAY,
    SATURDAY,
    SUNDAY,
)

_UNITED_KINGDOM = (
    Observance.fixed("New Year's Eve", 12, 31),
    Observance.fixed("Valentine's Day", 2, 14),
    Observance.easter("Shrove Tuesday", -47),
    Observance.easter("Ash Wednesday", -46),
    Observance.easter("Mothering Sunday", -21),
    Observance.fixed("April Fool's Day", 4, 1),
    Observance.easter("Palm Sunday", -7),
    Observance.easter("Maundy Thursday", -3),
    Observance.fixed("St George's Day", 4, 23),
    Observance.nth_weekday("Father's Day", 6, SUNDAY, 3),
    Observance.fixed("Halloween", 10, 31),
    Observance.nth_weekday("Remembrance Sunday", 11, SUNDAY, 2),
    Observance.fixed("Guy Fawkes Night", 11, 5),
    Observance.fixed("Christmas Eve", 12, 24),
)

_UNITED_STATES = (
    Observance.fixed("New Year's Eve", 12, 31),
    Observance.fixed("Valentine's Day", 2, 14),
    Observance.fixed("St Patrick's Day", 3, 17),
    Observance.fixed("April Fool's Day", 4, 1),
    Observance.nth_weekday("Mother's Day", 5, SUNDAY, 2),
    Observance.nth_weekday("Father's Day", 6, SUNDAY, 3),
    Observance.fixed("Halloween", 10, 31),
    Observance.fixed("Christmas Eve", 12, 24),
)

_CANADA = (
    Observance.fixed("New Year's Eve", 12, 31),
    Observance.fixed("Valentine's Day", 2, 14),
    Observance.fixed("St Patrick's Day", 3, 17),
    Observance.nth_weekday("Mother's Day", 5, SUNDAY, 2),
    Observance.nth_weekday("Father's Day", 6, SUNDAY, 3),
    Observance.fixed("Halloween", 10, 31),
    Observance.fixed("Christmas Eve", 12, 24),
)

_OBSERVANCES_RESEARCHED = {
    "BG": (
        Observance.fixed("St. John the Baptist's Day", 1, 7),
        Observance.fixed("Trifon Zarezan", 2, 14),
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.fixed("Baba Marta Day", 3, 1),
        Observance.fixed("International Women's Day", 3, 8),
        Observance.fixed("St. Demetrius' Day", 10, 26),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "BR": (
        Observance.fixed("Dia dos Namorados", 6, 12),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 2),
        Observance.nth_weekday("Father's Day", 8, SUNDAY, 2),
        Observance.fixed("Grandparents' Day", 7, 26),
        Observance.fixed("Saint John's Day", 6, 24),
        Observance.easter("Carnival Monday", -48),
        Observance.easter("Carnival Tuesday", -47),
        Observance.easter("Ash Wednesday", -46),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "CN": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.fixed("Women's Day", 3, 8),
        Observance.fixed("Youth Day", 5, 4),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 2),
        Observance.fixed("Children's Day", 6, 1),
        Observance.nth_weekday("Father's Day", 6, SUNDAY, 3),
        Observance.fixed("Army Day", 8, 1),
        Observance.fixed("Teachers' Day", 9, 10),
        Observance.fixed("Singles' Day", 11, 11),
    ),
    "CT": (
        Observance.fixed("Sant Jordi", 4, 23),
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.fixed("International Women's Day", 3, 8),
        Observance.fixed("Father's Day", 3, 19),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 1),
        Observance.fixed("Revetlla de Sant Joan", 6, 23),
        Observance.easter("Fat Thursday", -52),
        Observance.easter("Carnival Tuesday", -47),
        Observance.fixed("Halloween", 10, 31),
        Observance.fixed("La Castanyada", 10, 31),
        Observance.fixed("All Souls' Day", 11, 2),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "CZ": (
        Observance.fixed("Epiphany", 1, 6),
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.fixed("International Women's Day", 3, 8),
        Observance.fixed("Burning of the Witches", 4, 30),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 2),
        Observance.nth_weekday("Father's Day", 6, SUNDAY, 3),
        Observance.fixed("Halloween", 10, 31),
        Observance.fixed("All Souls' Day", 11, 2),
        Observance.fixed("Saint Barbara's Day", 12, 4),
        Observance.fixed("Saint Nicholas Day", 12, 5),
        Observance.fixed("Saint Lucy's Day", 12, 13),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "DE": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.easter("Women's Carnival", -52),
        Observance.easter("Rose Monday", -48),
        Observance.easter("Shrove Tuesday", -47),
        Observance.easter("Ash Wednesday", -46),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 2),
        Observance.fixed("St. Martin's Day", 11, 11),
        Observance.nth_weekday("People's Day of Mourning", 11, SUNDAY, 3),
        Observance.fixed("St. Nicholas Day", 12, 6),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "DK": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.easter("Fastelavn", -49),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 2),
        Observance.fixed("Sankt Hans Aften", 6, 23),
        Observance.fixed("Halloween", 10, 31),
        Observance.fixed("Mortensaften", 11, 10),
        Observance.fixed("St Lucia's Day", 12, 13),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "EE": (
        Observance.fixed("Friend's Day", 2, 14),
        Observance.fixed("Walpurgis Night", 4, 30),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 2),
        Observance.nth_weekday("Grandparents' Day", 9, SUNDAY, 2),
        Observance.fixed("Halloween", 10, 31),
        Observance.fixed("All Souls' Day", 11, 2),
        Observance.fixed("St. Martin's Day", 11, 10),
        Observance.nth_weekday("Father's Day", 11, SUNDAY, 2),
        Observance.fixed("St. Catherine's Day", 11, 25),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "ES": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.easter("Carnival Tuesday", -47),
        Observance.fixed("Father's Day", 3, 19),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 1),
        Observance.fixed("Grandparents' Day", 7, 26),
        Observance.fixed("Halloween", 10, 31),
        Observance.fixed("All Souls' Day", 11, 2),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "FI": (
        Observance.fixed("Runeberg Day", 2, 5),
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.fixed("Kalevala Day", 2, 28),
        Observance.fixed("Mikael Agricola Day", 4, 9),
        Observance.fixed("J.V. Snellman Day", 5, 12),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 2),
        Observance.fixed("Aleksis Kivi Day", 10, 10),
        Observance.fixed("Finnish Swedish Heritage Day", 11, 6),
        Observance.nth_weekday("Father's Day", 11, SUNDAY, 2),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
        Observance.easter("Shrove Tuesday", -47),
    ),
    "FR": (
        Observance.fixed("Epiphany", 1, 6),
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.nth_weekday("Grandmothers' Day", 3, SUNDAY, 1),
        Observance.fixed("April Fools' Day", 4, 1),
        Observance.easter("Mardi Gras", -47),
        Observance.last_weekday("Mother's Day", 5, SUNDAY),
        Observance.nth_weekday("Father's Day", 6, SUNDAY, 3),
        Observance.fixed("Music Day", 6, 21),
        Observance.fixed("Halloween", 10, 31),
        Observance.fixed("All Souls' Day", 11, 2),
        Observance.fixed("Saint Catherine's Day", 11, 25),
        Observance.fixed("Saint Nicholas' Day", 12, 6),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "GR": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.orthodox_easter("Tsiknopempti", -59),
        Observance.orthodox_easter("Cheesefare Sunday", -49),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 2),
        Observance.nth_weekday("Father's Day", 6, SUNDAY, 3),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "HR": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.easter("Shrove Tuesday", -47),
        Observance.fixed("Father's Day", 3, 19),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 2),
        Observance.fixed("Halloween", 10, 31),
        Observance.fixed("All Souls' Day", 11, 2),
        Observance.fixed("St. Nicholas Day", 12, 6),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "HU": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.fixed("International Women's Day", 3, 8),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 1),
        Observance.nth_weekday("Father's Day", 6, SUNDAY, 3),
        Observance.fixed("All Souls' Day", 11, 2),
        Observance.fixed("Saint Nicholas Day", 12, 6),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
        Observance.easter("Carnival / Shrove Tuesday", -47),
        Observance.easter("Ash Wednesday", -46),
    ),
    "ID": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.fixed("Kartini Day", 4, 21),
        Observance.fixed("National Education Day", 5, 2),
        Observance.fixed("National Awakening Day", 5, 20),
        Observance.fixed("Pancasila Sanctity Day", 10, 1),
        Observance.fixed("National Batik Day", 10, 2),
        Observance.fixed("Youth Pledge Day", 10, 28),
        Observance.fixed("Heroes' Day", 11, 10),
        Observance.fixed("Mother's Day", 12, 22),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "IL": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.fixed("International Women's Day", 3, 8),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "IN": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 2),
        Observance.nth_weekday("Father's Day", 6, SUNDAY, 3),
        Observance.fixed("National Youth Day", 1, 12),
        Observance.fixed("Teachers' Day", 9, 5),
        Observance.fixed("Children's Day", 11, 14),
        Observance.fixed("New Year's Eve", 12, 31),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("International Women's Day", 3, 8),
        Observance.fixed("Halloween", 10, 31),
        Observance.fixed("Engineers' Day", 9, 15),
        Observance.fixed("National Doctors' Day", 7, 1),
    ),
    "IT": (
        Observance.fixed("Epiphany Eve", 1, 5),
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.easter("Carnival / Shrove Tuesday", -47),
        Observance.easter("Ash Wednesday", -46),
        Observance.fixed("International Women's Day", 3, 8),
        Observance.fixed("Father's Day", 3, 19),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 2),
        Observance.fixed("Grandparents' Day", 10, 2),
        Observance.fixed("Halloween", 10, 31),
        Observance.fixed("All Souls' Day", 11, 2),
        Observance.fixed("Saint Lucy's Day", 12, 13),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "JP": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.fixed("Hinamatsuri", 3, 3),
        Observance.fixed("White Day", 3, 14),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 2),
        Observance.nth_weekday("Father's Day", 6, SUNDAY, 3),
        Observance.fixed("Tanabata", 7, 7),
        Observance.fixed("Obon", 8, 15),
        Observance.fixed("Halloween", 10, 31),
        Observance.fixed("Shichi-Go-San", 11, 15),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("Omisoka", 12, 31),
    ),
    "KR": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.fixed("White Day", 3, 14),
        Observance.fixed("Black Day", 4, 14),
        Observance.fixed("Parents' Day", 5, 8),
        Observance.fixed("Teachers' Day", 5, 15),
        Observance.nth_weekday("Coming of Age Day", 5, MONDAY, 3),
        Observance.fixed("Pepero Day", 11, 11),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "LT": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.easter("Shrove Tuesday", -47),
        Observance.fixed("International Women's Day", 3, 8),
        Observance.fixed("Halloween", 10, 31),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "LV": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 2),
        Observance.fixed("Miķeļi", 9, 29),
        Observance.nth_weekday("Father's Day", 9, SUNDAY, 2),
        Observance.fixed("Halloween", 10, 31),
        Observance.fixed("Mārtiņi", 11, 10),
        Observance.fixed("Lāčplēsis Day", 11, 11),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "NL": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.easter("Carnival", -47),
        Observance.fixed("Remembrance Day", 5, 4),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 2),
        Observance.nth_weekday("Father's Day", 6, SUNDAY, 3),
        Observance.fixed("Halloween", 10, 31),
        Observance.fixed("All Saints' Day", 11, 1),
        Observance.fixed("All Souls' Day", 11, 2),
        Observance.fixed("St. Martin's Day", 11, 11),
        Observance.fixed("Sinterklaas", 12, 5),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "NO": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.nth_weekday("Mother's Day", 2, SUNDAY, 2),
        Observance.easter("Fastelavn", -49),
        Observance.easter("Shrove Tuesday", -47),
        Observance.fixed("St. John's Eve", 6, 23),
        Observance.fixed("Halloween", 10, 31),
        Observance.nth_weekday("Father's Day", 11, SUNDAY, 2),
        Observance.fixed("Saint Lucy's Day", 12, 13),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "PL": (
        Observance.fixed("Grandmother's Day", 1, 21),
        Observance.fixed("Grandfather's Day", 1, 22),
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.fixed("International Women's Day", 3, 8),
        Observance.fixed("Children's Day", 6, 1),
        Observance.fixed("Mother's Day", 5, 26),
        Observance.fixed("Father's Day", 6, 23),
        Observance.fixed("All Souls' Day", 11, 2),
        Observance.fixed("St Andrew's Day", 11, 30),
        Observance.fixed("St Nicholas Day", 12, 6),
        Observance.fixed("New Year's Eve", 12, 31),
        Observance.easter("Fat Thursday", -52),
        Observance.easter("Shrove Tuesday", -47),
    ),
    "PT": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.easter("Carnival / Shrove Tuesday", -47),
        Observance.fixed("Father's Day", 3, 19),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 1),
        Observance.fixed("Saint Anthony's Day", 6, 13),
        Observance.fixed("Saint John's Day", 6, 24),
        Observance.fixed("Saint Peter's Day", 6, 29),
        Observance.fixed("Grandparents' Day", 7, 26),
        Observance.fixed("Halloween", 10, 31),
        Observance.fixed("All Souls' Day", 11, 2),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "RO": (
        Observance.fixed("Dragobete", 2, 24),
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.fixed("Martisor", 3, 1),
        Observance.fixed("International Women's Day", 3, 8),
        Observance.orthodox_easter("Palm Sunday", -7),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 1),
        Observance.nth_weekday("Father's Day", 5, SUNDAY, 2),
        Observance.fixed("Halloween", 10, 31),
        Observance.fixed("Saint Nicholas Day", 12, 6),
        Observance.fixed("Anniversary of the 1989 Revolution", 12, 22),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "RU": (
        Observance.fixed("Old New Year", 1, 14),
        Observance.fixed("Tatiana Day", 1, 25),
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.orthodox_easter("Maslenitsa", -49),
        Observance.fixed("Cosmonautics Day", 4, 12),
        Observance.fixed("Day of Family, Love and Fidelity", 7, 8),
        Observance.fixed("Knowledge Day", 9, 1),
        Observance.last_weekday("Mother's Day", 11, SUNDAY),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "SA": (
        Observance.fixed("Mother's Day", 3, 21),
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "SE": (
        Observance.fixed("St. Knut's Day", 1, 13),
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.easter("Shrove Tuesday", -47),
        Observance.fixed("Walpurgis Night", 4, 30),
        Observance.last_weekday("Mother's Day", 5, SUNDAY),
        Observance.fixed("Halloween", 10, 31),
        Observance.nth_weekday("Father's Day", 11, SUNDAY, 2),
        Observance.fixed("St. Martin's Day", 11, 11),
        Observance.fixed("Saint Lucy's Day", 12, 13),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "SI": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.easter("Shrove Tuesday", -47),
        Observance.easter("Ash Wednesday", -46),
        Observance.fixed("International Women's Day", 3, 8),
        Observance.fixed("Father's Day", 3, 19),
        Observance.fixed("Mother's Day", 3, 25),
        Observance.fixed("Saint Nicholas Day", 12, 6),
        Observance.fixed("Saint Martin's Day", 11, 11),
        Observance.fixed("All Souls' Day", 11, 2),
        Observance.fixed("Halloween", 10, 31),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
        Observance.easter("Palm Sunday", -7),
    ),
    "SK": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.fixed("International Women's Day", 3, 8),
        Observance.easter("Shrove Tuesday", -47),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 2),
        Observance.nth_weekday("Father's Day", 6, SUNDAY, 3),
        Observance.fixed("Halloween", 10, 31),
        Observance.fixed("All Souls' Day", 11, 2),
        Observance.fixed("Saint Nicholas Day", 12, 6),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "TH": (
        Observance.nth_weekday("National Children's Day", 1, SATURDAY, 2),
        Observance.fixed("Teachers' Day", 1, 16),
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
        Observance.fixed("Halloween", 10, 31),
    ),
    "TR": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.fixed("International Women's Day", 3, 8),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 2),
        Observance.nth_weekday("Father's Day", 6, SUNDAY, 3),
        Observance.fixed("Ataturk Commemoration Day", 11, 10),
        Observance.fixed("Teachers' Day", 11, 24),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "TW": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.fixed("Women's Day", 3, 8),
        Observance.fixed("Arbor Day", 3, 12),
        Observance.fixed("White Day", 3, 14),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 2),
        Observance.fixed("Father's Day", 8, 8),
        Observance.fixed("Halloween", 10, 31),
        Observance.fixed("Sun Yat-sen's Birthday", 11, 12),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
    "UA": (
        Observance.fixed("Day of Dignity and Freedom", 11, 21),
        Observance.nth_weekday("Vyshyvanka Day", 5, THURSDAY, 3),
        Observance.nth_weekday("Mother's Day", 5, SUNDAY, 2),
        Observance.nth_weekday("Father's Day", 6, SUNDAY, 3),
        Observance.fixed("Saint Nicholas Day", 12, 6),
        Observance.fixed("Saint Valentine's Day", 2, 14),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
        Observance.fixed("Epiphany", 1, 6),
    ),
    "VN": (
        Observance.fixed("Valentine's Day", 2, 14),
        Observance.fixed("Vietnamese Doctors' Day", 2, 27),
        Observance.fixed("International Women's Day", 3, 8),
        Observance.fixed("International Children's Day", 6, 1),
        Observance.fixed("Vietnamese Women's Day", 10, 20),
        Observance.fixed("Vietnamese Teachers' Day", 11, 20),
        Observance.fixed("Vietnam People's Army Day", 12, 22),
        Observance.fixed("Christmas Eve", 12, 24),
        Observance.fixed("New Year's Eve", 12, 31),
    ),
}

OBSERVANCES_BY_COUNTRY: dict[str, tuple[Observance, ...]] = {
    "GB": _UNITED_KINGDOM,
    "US": _UNITED_STATES,
    "CA": _CANADA,
    **_OBSERVANCES_RESEARCHED,
}


def observances_for_country(country_code: str) -> tuple[Observance, ...]:
    """Return the observances defined for ``country_code`` (empty if none)."""
    return OBSERVANCES_BY_COUNTRY.get(country_code.upper(), ())


def observance_dates(country_code: str, year: int) -> dict[date, str]:
    """Return ``{date: name}`` for every observance of a country in a year."""
    result: dict[date, str] = {}
    for observance in observances_for_country(country_code):
        result[observance.date_for(year)] = observance.name
    return result
